### ISSUE TITLE
YJL introduction

### ISSUE THREAD

**Issue by nickynicolson** [WFO-ID-pilots/.github#4]
@yjkiwilee - please add yourself (name / affiliation and [ORCID](https://orcid.org) if you have one) to the list of people in the organisation README page at: https://github.com/WFO-ID-pilots/.github/blob/main/profile/README.md

If you can mail me a paragraph about yourself - your course, interests, career aspirations etc - then I can send an introduction to the project partners and to the department at Kew.

**Comment by yjkiwilee** [comment]
@nickynicolson - I've created a pull request with the updated README.md document and sent the introductory paragraph to your email.
